set(SUPPORTS_CXX "FALSE")
if("${COMPILER}" STREQUAL "intel")
  set(FC_AUTO_R8 "-r8")
  set(MPIFC "mpiifort")
  set(FFLAGS_NOOPT "-O0")
  set(CXX_LDFLAGS "-cxxlib")
  set(SUPPORTS_CXX "TRUE")
  set(FFLAGS "-qno-opt-dynamic-align  -convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -fp-model source")
  set(FIXEDFLAGS "-fixed -132")
  set(SCC "icc")
  set(SFC "ifort")
  set(MPICC "mpiicc")
  set(MPI_PATH "/public/software/mpi/intelmpi/2021.3.0")
  set(CFLAGS "-qno-opt-dynamic-align -fp-model precise -std=gnu99")
  set(ESMF_LIBDIR "/public/home/cuit_lsh/esmf-ESMF_8_1_1/lib")
  set(MPICXX "mpiicpc")
  set(FREEFLAGS "-free")
  set(CXX_LINKER "FORTRAN")
  set(SCXX "icpc")
endif()
set(CPPDEFS "${CPPDEFS}  -DCESMCOUPLED")
if("${MODEL}" STREQUAL "pop")
  set(CPPDEFS "${CPPDEFS}  -D_USE_FLOW_CONTROL")
endif()
if("${MODEL}" STREQUAL "ufsatm")
  set(FFLAGS "${FFLAGS}  $(FC_AUTO_R8)")
  set(CPPDEFS "${CPPDEFS}  -DSPMD")
endif()
if("${MODEL}" STREQUAL "mom")
  set(FFLAGS "${FFLAGS}  $(FC_AUTO_R8) -Duse_LARGEFILE")
endif()
if("${COMPILER}" STREQUAL "intel")
  set(CPPDEFS "${CPPDEFS} -DFORTRANUNDERSCORE -DCPRINTEL")
  set(SLIBS "${SLIBS}  -L/public/software/mathlib/netcdf/4.4.1/intel/lib -lnetcdff -lnetcdf")
  set(SLIBS "${SLIBS}  -L/public/software/mathlib/lapack/intel/3.8.0/lib -llapack")
  set(SLIBS "${SLIBS}  -L/public/software/mathlib/BLAS/3.10.0/lib -lblas")
  if("${compile_threaded}" STREQUAL "TRUE")
    set(FFLAGS "${FFLAGS}  -qopenmp")
    set(CFLAGS "${CFLAGS}  -qopenmp")
  endif()
  if("${DEBUG}" STREQUAL "TRUE")
    set(FFLAGS "${FFLAGS}  -O0 -g -check uninit -check bounds -check pointers -fpe0")
    set(CFLAGS "${CFLAGS}  -O0 -g")
  endif()
  if("${DEBUG}" STREQUAL "FALSE")
    set(FFLAGS "${FFLAGS}  -O2 -debug minimal")
    set(CFLAGS "${CFLAGS}  -O2 -debug minimal")
  endif()
  if("${MPILIB}" STREQUAL "intelmpi")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${compile_threaded}" STREQUAL "TRUE")
    set(LDFLAGS "${LDFLAGS}  -qopenmp")
  endif()
endif()
if("${MODEL}" STREQUAL "ufsatm")
  set(INCLDIR "${INCLDIR}  -I$(EXEROOT)/atm/obj/FMS")
endif()
